#!/bin/bash

usage() {
    echo "Error: Session name is missing."
    echo "Usage: forge -n <session_name>"
    exit 1
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -n|--name) name="$2"; shift;;
        *) usage;;
    esac
    shift
done

if [ -z "$name" ]; then
    usage
fi

path=$(pwd)

tmux new-session -d -s "$name"

tmux rename-window -t "$name:1" "Anvil"
tmux send-keys -t "$name:1" "cd $path && nvim ." C-m

tmux new-window -t "$name:2" -n "Furnace"
tmux send-keys -t "$name:2" "cd $path && clear" C-m

tmux new-window -t "$name:3" -n "Smithy"
tmux send-keys -t "$name:3" "cd ~ && clear" C-m

tmux attach-session -t "$name"
